### ISSUE TITLE
No content in the report in GnuCash

### ISSUE THREAD

**Issue by alensiljak** [sdementen/gnucash-utilities#7]
I'll leave #4 as the solution is correcting the path that gets written into config.user.

Now the issue is that the report in GnuCash (i.e. report_simple.py) is always blank.
Need to troubleshoot further. No errors in the trace file, though.

In the Process Hacker, when the report is refreshed in GnuCash, I see pythonw process starting. I'm suspecting something is wrong with the path here, too:
```
    (define (start-program)
      (set! program (gnc-spawn-process-async
                     (list "d:\\lib\\python36-32\\pythonw.exe"
                           (gnc-build-dotgnucash-path "report_simple\report_simple.py")
                           (qof-session-get-url (gnc-get-current-session)))
                     #t)))
```

**Comment by alensiljak** [comment]
It's too late and I'm not thinking straight any longer.
I have adjusted my report_simple.py to send the second parameter:
```
if __name__ == '__main__':
    execute_report(generate_report, None)
```
and now finally some output in GnuCash:
```
Traceback (most recent call last):
  File "d:\src\gnucash-utilities\piecash_utilities\report\report.py", line 124, in execute_report
    s = generate_report(book_url)
  File "d:\src\gnucash-utilities\piecash_utilities\report\report.py", line 91, in wrapped
    book_url = (book_url
AttributeError: 'NoneType' object has no attribute 'replace'
```

**Comment by alensiljak** [comment]
And, yes, after I changed it to
```
if __name__ == '__main__':
    execute_report(generate_report, "test")
```
things started working!
```
Hello world from python !
```
You rock! :) 
Something to play with over the weekend, I guess.
Now, changing the report_simple.py reflects changes on the fly. It is enough to refresh the report. Fantastic.

**Comment by alensiljak** [comment]
Considering that the report_simplest.py already contains
```
if __name__ == '__main__':
    execute_report(generate_report, book_url=sys.argv[1])
```
does this mean that book_url is not being passed from GnuCash?

**Comment by alensiljak** [comment]
Oh, and
```
(gnc-build-dotgnucash-path "report_simple\report_simple.py")
```
needs to be 
```
(gnc-build-dotgnucash-path "report_simple\\report_simple.py")
```
otherwise there's no output.

**Comment by alensiljak** [comment]
Not sure why the [docs](http://gnucash-utilities.readthedocs.io/en/stable/doc/doc.html#a-simple-report) still show
```
if __name__ == '__main__':
    execute_report(generate_report)
```
even though the code has the parameter
```
if __name__ == '__main__':
    execute_report(generate_report, book_url=sys.argv[1])
```
That's what was confusing me from the start.

**Comment by alensiljak** [comment]
Still, I can't display the book_url variable. Getting
```
Hello world from python !
{book_url}
```
in the output.

**Comment by alensiljak** [comment]
#6 Fixes this by correcting the path to the .py report script.
